### ISSUE TITLE
hw-bits-0.0.0.6 crashes GHC 7.10.3 in 32-bit Linux builds

### ISSUE THREAD

**Issue by peti** [haskell-works/hw-bits#1]
The package compiles fine on 64-bit Linux, but not on 32 bit:

```
[  111s] [ 9 of 15] Compiling HaskellWorks.Data.Bits.PopCount.PopCount1 ( src/HaskellWorks/Data/Bits/PopCount/PopCount1.hs, dist/build/HaskellWorks/Data/Bits/PopCount/PopCount1.o )
[  111s] ghc: panic! (the 'impossible' happened)
[  111s]   (GHC version 7.10.3 for i386-unknown-linux):
[  111s]    getRegister(x86) I64[R1 + 3]
```

Is this a known problem?

**Comment by newhoggy** [comment]
I've not actually been building this on any 32-bit architecture, so I've not been aware of the problem.

For performance, I rely on the`Data.Bits.popCount` being fast, and I achieve this with the `-msse4.2` flag, which allows GHC use built-in CPU `popCnt` instruction.  I'm surprised this should cause an issue on 32-bit architectures.  I had thought GHC would fall back a slow implementation if the architecture did not support it.

**Comment by peti** [comment]
Well, I don't know. All I can say is that the package doesn't compile. I am sorry that I cannot be more helpful.

**Comment by newhoggy** [comment]
Leaving a link here to know where to report GHC issues: https://ghc.haskell.org/trac/ghc/newticket

**Comment by peti** [comment]
According to https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using.html#platform-specific-flags, `-msse4.2` means:

> Use the SSE4.2 instruction set to implement some floating point and bit operations when using the native code generator. The resulting compiled code will only run on processors that support SSE4.2 (Intel Core i7 and later).

So I'd say that this flag is clearly wrong for i586 targets.

**Comment by newhoggy** [comment]
There is a section in https://www.haskell.org/cabal/users-guide/developing-packages.html named "Resolution of Conditions and Flags".

I wonder if I that will help get this project to compile on those platforms?

Unfortunately, I don't have an i586 target to test on.

**Comment by peti** [comment]
> I don't have an i586 target to test on.

Do you realize that you virtualize pretty much any system you please with tools like [qemu](http://wiki.qemu.org/Main_Page)? We're not running those builds on i586 machines either.

**Comment by peti** [comment]
Ping?

**Comment by newhoggy** [comment]
Does this work for you?

https://github.com/haskell-works/hw-bits/pull/2
