### ISSUE TITLE
Please revise old versions

### ISSUE THREAD

**Issue by gwils** [haskell-works/hw-bits#79]
If you have time, please revise versions 0.7.1.1 to 0.7.1.5 so that they do not try to build on ghc 7.10

https://matrix.hackage.haskell.org/#/package/hw-bits/0.7.1.5/ghc-7.10.3@1586840835

You can do so by either raising the base lower bound or adding `other-extensions: TypeApplications`.

**Comment by newhoggy** [comment]
All done!  I'll leave this ticket open for a short while to see if the matrix clears.

**Comment by gwils** [comment]
Unfortunately the matrix builders seem to be stuck at the moment. I've pinged Herbert about it.

**Comment by newhoggy** [comment]
The table looks smaller than before with ghc-8 columns missing, did something go wrong?

https://matrix.hackage.haskell.org/#/package/hw-bits/0.7.1.5/ghc-7.10.3@1587882225

**Comment by gwils** [comment]
It looks like it's all there for me? Maybe we were still waiting on some building. What happens if you refresh?

**Comment by newhoggy** [comment]
Just refreshed and I see it.  Probably ran overnight.  Thanks!
